### ISSUE TITLE
Contract methods naming guideline

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/NEPs#101] opened 2020-07-25 19:54 UTC
We need to define what is the contract methods and parameters naming guideline.
Specifically, we have right now snake case used in Rust based contracts and camel case in AssemblyScript.

Worth noting that Solidity uses camel case, because it gets surfaced in the JavaScript.
In our case, we right now are using snake case in JavaScript.

We need to decide on either and codify it in the meta-standard.

**Comment by nearmax** [comment] 2020-07-25 20:36
A duplicate of https://github.com/nearprotocol/NEPs/issues/96 Contract languages can choose whatever language specific guideline but when compiled into Wasm our near-sdk-* should expose it as both snake case and came case, see https://github.com/near/near-sdk-rs/issues/209

**Closed by nearmax** 2020-07-25 20:36 UTC
